#!/bin/sh
#
# Starts dvrui.
#

# Allow a few customizations from a config file
test -r /etc/default/dvrui && . /etc/default/dvrui

start() {
	printf "Starting dvrui: "

	start-stop-daemon -S -b -q -m -p /var/run/dvrui.pid \
		--exec python3 -- /etc/dvrui/app.py $DVRUI_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping dvrui: "
	start-stop-daemon -K -q -p /var/run/dvrui.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
