#!/bin/sh
#
# Starts pixelpilot.
#

# Allow a few customizations from a config file
test -r /etc/default/pixelpilot && . /etc/default/pixelpilot

start() {
	printf "Starting pixelpilot: "

	start-stop-daemon -S -b -q -p /var/run/pixelpilot.pid \
		--exec /usr/bin/pixelpilot.sh -- $PIXELPILOT_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping pixelpilot: "
	start-stop-daemon -K -q -p /var/run/pixelpilot.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
