default normal

label normal
  kernel /boot/Image
  fdtdir /boot
  append quiet loglevel=1 root=PARTLABEL=rootfs ro earlycon rootwait init=/init

label verbose
  kernel /boot/Image
  fdtdir /boot
  append loglevel=8 root=PARTLABEL=rootfs ro earlycon rootwait init=/init console=tty0 console=ttyFIQ0,1500000n8 console=ttyS2,1500000n8
