#!/bin/sh

# Autodetect 8812au, 8812eu and 8812cu cards

for i in $(find /sys/class/net/ -maxdepth 1 -type l | sort)
do
   if udevadm info $i | grep -qE 'ID_USB_DRIVER=(rtl88xxau_wfb|rtl88x2eu|rtl88x2cu)'
   then
         echo $(basename $i)
   fi
done
