ROCKCHIP_MPP_VERSION = c2c1ee502b3a26efebcf843f7a0aeb4d172c6237
ROCKCHIP_MPP_SITE = https://github.com/rockchip-linux/mpp.git
ROCKCHIP_MPP_SITE_METHOD = git
ROCKCHIP_MPP_INSTALL_STAGING = YES
ROCKCHIP_MPP_INSTALL_TARGET = YES

ROCKCHIP_MPP_CONF_OPTS = \
	-DRKPLAT=ON \
	-DHAVE_DRM=ON

$(eval $(cmake-package))
