ROCKCHIP_MPP_VERSION = bf7c3be28d43f71544845d45400bd84de827b6bf
ROCKCHIP_MPP_SITE = https://github.com/rockchip-linux/mpp.git
ROCKCHIP_MPP_SITE_METHOD = git
ROCKCHIP_MPP_INSTALL_STAGING = YES
ROCKCHIP_MPP_INSTALL_TARGET = YES

ROCKCHIP_MPP_CONF_OPTS = \
	-DRKPLAT=ON \
	-DHAVE_DRM=ON

$(eval $(cmake-package))
