name: AutoBuild

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: |
        echo "cd code dir ${{ github.workspace }}"
        cd ${{ github.workspace }}/build
        sudo ./release.sh ${GITHUB_SHA} ${GITHUB_REF}

    - name: Upload test image
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ${{ github.workspace }}/build/*.xz
